# Generated by Django 5.2.6 on 2025-10-05 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_industries_business_industry_business_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrytag',
            options={'ordering': ('name',), 'verbose_name': 'Industry tag', 'verbose_name_plural': 'Industry tags'},
        ),
        migrations.RemoveField(
            model_name='businessstudenttracking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businessstudenttracking',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='businessstudenttracking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='businessstudenttracking',
            name='last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessstudenttracking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessstudenttracking',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessstudenttracking',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessstudenttracking',
            name='tracking_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='allow_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students/avatars/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
