# Generated by Django 5.2.6 on 2025-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_industrytag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrytag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
