# Generated by Django 5.2.6 on 2025-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_industrytag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltag',
            options={'ordering': ('name',), 'verbose_name': 'Skill tag', 'verbose_name_plural': 'Skill tags'},
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
