# Generated by Django 5.2.6 on 2025-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_skilltag_options_alter_skilltag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstudenttracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='businessstudenttracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
