# Generated by Django 5.2.6 on 2025-10-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_college_university_studentprofile_college_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStudentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacted'), ('interview', 'Interview/Meeting'), ('engaged', 'Engaged/Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='lead', max_length=20)),
                ('contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trackings', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_trackings', to='organizations.business')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_trackings', to='organizations.studentprofile')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('business', 'student')},
            },
        ),
    ]
