# Generated by Django 5.2.6
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0011_organizationstudenttracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, db_index=True)),
                ("phone", models.CharField(max_length=50, blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=120, blank=True, null=True)),
                ("country", models.CharField(max_length=100, blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="parent_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, db_index=True)),
                ("date", models.DateField()),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("completed_lessons", models.PositiveIntegerField(default=0)),
                ("average_score", models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("progress_percent", models.PositiveSmallIntegerField(
                    default=0,
                    validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                )),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress_records", to="parents.parentprofile")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_progress", to="organizations.studentprofile")),
            ],
            options={
                "ordering": ("-date", "-updated_at", "-id"),
                "unique_together": {("parent", "student", "date")},
            },
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="students",
            field=models.ManyToManyField(blank=True, related_name="parents", to="organizations.studentprofile"),
        ),
    ]
