# Generated by Django 5.2.6 on 2025-10-03 22:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_industries_business_industry_business_address_and_more'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'ordering': ('-date', '-updated_at', '-id')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # don't touch the DB (column already exists)
            state_operations=[
                migrations.AddField(
                    model_name='studentprogress',
                    name='parent',
                    field=models.ForeignKey(
                        to='parents.parentprofile',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='progress_records',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # don't touch the DB (column already exists)
            state_operations=[
                migrations.AddField(
                    model_name='studentprogress',
                    name='student',
                    field=models.ForeignKey(
                        to='organizations.studentprofile',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='daily_progress',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('parent', 'student', 'date')},
        ),
    ]
